#!/usr/bin/env python3
"""
fetch_fonts.py - vendor the launcher's typefaces.

The launcher must render identically on a machine that has never had a network
connection, and its content security policy admits no outside origins, so the
faces are committed rather than linked. IBM Plex is licensed under the SIL Open
Font License 1.1, which permits exactly this.

    python3 launcher/tools/fetch_fonts.py

Re-run only to change the set. The output is deterministic apart from the
upstream font version, which is recorded in the generated CSS.
"""

import re
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "ui" / "src" / "fonts"

# A modern UA is what makes Google Fonts serve woff2 rather than truetype.
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36"

FAMILIES = "family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans+Condensed:wght@400;500;600"
CSS_URL = f"https://fonts.googleapis.com/css2?{FAMILIES}&display=block"


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    css = get(CSS_URL).decode("utf-8")

    # Google emits one @font-face per family/weight/subset. We keep the latin
    # ones: the launcher's own strings are English, and a player's file paths
    # fall back to the system face, which is the right behaviour anyway.
    blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S)
    kept = []
    for subset, block in blocks:
        if subset not in ("latin", "latin-ext"):
            continue
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: (\d+)", block).group(1)

        name = f"{family.replace(' ', '-').lower()}-{weight}-{subset}.woff2"
        (OUT / name).write_bytes(get(url))
        kept.append(
            block.replace(f"url({url})", f"url(./{name})")
            .replace("@font-face {", "@font-face {\n  /* vendored: see launcher/tools/fetch_fonts.py */")
        )
        print(f"{name}  {(OUT / name).stat().st_size} bytes")

    header = (
        "/*\n"
        " * IBM Plex, vendored.\n"
        " *\n"
        " * Generated by launcher/tools/fetch_fonts.py - do not edit by hand.\n"
        " * IBM Plex is (c) IBM Corp, licensed under the SIL Open Font License 1.1;\n"
        " * see OFL.txt beside these files.\n"
        " */\n\n"
    )
    (OUT / "fonts.css").write_text(header + "\n\n".join(kept) + "\n")
    print(f"{OUT / 'fonts.css'}  {len(kept)} faces")


if __name__ == "__main__":
    main()
