-- Tomorrow's Ash - classless ability trees
--
-- GENERATED by tools/gen_trees.py. Edit that, not this file.
--
-- Every spell id below was verified against the world database before
-- this file was written: either trainable (trainer_spell, which also
-- supplies the level requirement) or a member of a rank chain
-- (spell_ranks). The generator refuses to emit SQL otherwise.
--
-- Pool total: 200 points against a level 80 budget of 71 (36% affordable).
-- See docs/PHASE2-BUDGET.md for why that ratio matters.

DELETE FROM `classless_node` WHERE `id` BETWEEN 1 AND 9999;
DELETE FROM `classless_tree` WHERE `id` BETWEEN 1 AND 9999;

INSERT INTO `classless_tree` (`id`, `name`, `description`, `sort_order`) VALUES
  (1, 'Fire', 'Destructive flame. The highest damage, and the least subtlety.', 10),
  (2, 'Frost', 'Cold and control. Slower, safer, relentless.', 20),
  (3, 'Arcane', 'Raw magic, bent to utility as often as to harm.', 30),
  (4, 'Holy', 'Light and mending. Keeps others upright.', 40),
  (5, 'Shadow', 'Rot, dread and slow ruin.', 50),
  (6, 'Nature', 'Growth, snare and restoration.', 60),
  (7, 'Sword Mastery', 'Weapon craft. Rewards closing the distance.', 70),
  (8, 'Defense', 'Shields, shouts and staying alive.', 80),
  (9, 'Stealth', 'Shadow and opportunity. Strike from where none look.', 90),
  (10, 'Marksmanship', 'Range, traps and patience.', 100);

INSERT INTO `classless_node`
  (`id`, `tree_id`, `spell_id`, `name`, `description`, `tier`, `cost`, `required_level`, `requires_node`, `sort_order`)
VALUES
  (101, 1, 133, 'Fireball', '', 1, 2, 1, 0, 10),
  (102, 1, 2136, 'Fire Blast', '', 2, 3, 6, 101, 20),
  (103, 1, 2120, 'Flamestrike', '', 3, 4, 16, 102, 30),
  (104, 1, 2948, 'Scorch', '', 4, 5, 22, 103, 40),
  (105, 1, 11113, 'Blast Wave', '', 5, 6, 40, 104, 50),
  (201, 2, 116, 'Frostbolt', '', 1, 2, 4, 0, 10),
  (202, 2, 122, 'Frost Nova', '', 2, 3, 10, 201, 20),
  (203, 2, 10, 'Blizzard', '', 3, 4, 20, 202, 30),
  (204, 2, 120, 'Cone of Cold', '', 4, 5, 26, 203, 40),
  (205, 2, 45438, 'Ice Block', '', 5, 6, 30, 204, 50),
  (301, 3, 1459, 'Arcane Intellect', '', 1, 2, 1, 0, 10),
  (302, 3, 5143, 'Arcane Missiles', '', 2, 3, 8, 301, 20),
  (303, 3, 1449, 'Arcane Explosion', '', 3, 4, 14, 302, 30),
  (304, 3, 1953, 'Blink', '', 4, 5, 20, 303, 40),
  (305, 3, 2139, 'Counterspell', '', 5, 6, 24, 304, 50),
  (401, 4, 1243, 'Power Word: Fortitude', '', 1, 2, 1, 0, 10),
  (402, 4, 17, 'Power Word: Shield', '', 2, 3, 6, 401, 20),
  (403, 4, 139, 'Renew', '', 3, 4, 8, 402, 30),
  (404, 4, 2054, 'Heal', '', 4, 5, 16, 403, 40),
  (405, 4, 2061, 'Flash Heal', '', 5, 6, 20, 404, 50),
  (501, 5, 589, 'Shadow Word: Pain', '', 1, 2, 4, 0, 10),
  (502, 5, 172, 'Corruption', '', 2, 3, 4, 501, 20),
  (503, 5, 980, 'Curse of Agony', '', 3, 4, 8, 502, 30),
  (504, 5, 8092, 'Mind Blast', '', 4, 5, 10, 503, 40),
  (505, 5, 689, 'Drain Life', '', 5, 6, 14, 504, 50),
  (601, 6, 1126, 'Mark of the Wild', '', 1, 2, 1, 0, 10),
  (602, 6, 774, 'Rejuvenation', '', 2, 3, 4, 601, 20),
  (603, 6, 339, 'Entangling Roots', '', 3, 4, 8, 602, 30),
  (604, 6, 8936, 'Regrowth', '', 4, 5, 12, 603, 40),
  (605, 6, 2637, 'Hibernate', '', 5, 6, 18, 604, 50),
  (701, 7, 78, 'Heroic Strike', '', 1, 2, 1, 0, 10),
  (702, 7, 772, 'Rend', '', 2, 3, 4, 701, 20),
  (703, 7, 6343, 'Thunder Clap', '', 3, 4, 6, 702, 30),
  (704, 7, 845, 'Cleave', '', 4, 5, 20, 703, 40),
  (705, 7, 5308, 'Execute', '', 5, 6, 24, 704, 50),
  (801, 8, 6673, 'Battle Shout', '', 1, 2, 1, 0, 10),
  (802, 8, 100, 'Charge', '', 2, 3, 4, 801, 20),
  (803, 8, 72, 'Shield Bash', '', 3, 4, 12, 802, 30),
  (804, 8, 6572, 'Revenge', '', 4, 5, 14, 803, 40),
  (805, 8, 2565, 'Shield Block', '', 5, 6, 16, 804, 50),
  (901, 9, 1784, 'Stealth', '', 1, 2, 1, 0, 10),
  (902, 9, 53, 'Backstab', '', 2, 3, 4, 901, 20),
  (903, 9, 1776, 'Gouge', '', 3, 4, 6, 902, 30),
  (904, 9, 2983, 'Sprint', '', 4, 5, 10, 903, 40),
  (905, 9, 8676, 'Ambush', '', 5, 6, 18, 904, 50),
  (1001, 10, 1978, 'Serpent Sting', '', 1, 2, 4, 0, 10),
  (1002, 10, 3044, 'Arcane Shot', '', 2, 3, 6, 1001, 20),
  (1003, 10, 5116, 'Concussive Shot', '', 3, 4, 8, 1002, 30),
  (1004, 10, 2643, 'Multi-Shot', '', 4, 5, 18, 1003, 40),
  (1005, 10, 1499, 'Freezing Trap', '', 5, 6, 20, 1004, 50);
