--
-- Body-type stat curves for player_class_stats.
--
-- GENERATED by tools/gen_body_types.py - do not hand-edit; re-run the tool.
--
-- The numbers in docs/BODY-TYPES.md section 2 were approved on 2026-08-26 and
-- never turned into a migration, so until now the three body types were
-- numerically identical to stock Paladin, Shaman and Mage wearing new names.
--
-- Vanguard (Paladin, class 2) is the reference point and is not touched.
-- Skirmisher (Shaman, 7) and Adept (Mage, 8) are moved onto the approved
-- curve: linear from no change at level 1, through the approved level 60 row,
-- to the approved level 80 row. The generator refuses to emit unless both
-- anchors come out exactly and no stat decreases with level.
--
-- Reversible: classless_class_stats_backup keeps every original row.
--

CREATE TABLE IF NOT EXISTS `classless_class_stats_backup` (
  `Class`     TINYINT UNSIGNED NOT NULL,
  `Level`     TINYINT UNSIGNED NOT NULL,
  `BaseHP`    INT UNSIGNED NOT NULL,
  `BaseMana`  INT UNSIGNED NOT NULL,
  `Strength`  INT NOT NULL,
  `Agility`   INT NOT NULL,
  `Stamina`   INT NOT NULL,
  `Intellect` INT NOT NULL,
  `Spirit`    INT NOT NULL,
  PRIMARY KEY (`Class`, `Level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='mod-classless: pre-body-type player_class_stats, so the curve can be undone';

-- INSERT IGNORE so re-running never overwrites a real original with a value
-- this migration itself wrote.
INSERT IGNORE INTO `classless_class_stats_backup`
  (`Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
SELECT `Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`
FROM `player_class_stats` WHERE `Class` IN (8);


-- Adept (class 8): 0 of 80 levels differ from stock.
