--
-- Remove class restrictions from weapons and armor.
--
-- GENERATED by tools/audit_items.py - do not hand-edit; re-run the tool.
--
-- Why: three body types exist on Ashmorrow, each one a stock class underneath
-- (Paladin / Shaman / Mage). AllowableClass is still enforced in
-- Player::CanUseItem (PlayerStorage.cpp:2372), so 2849 weapon and armor
-- rows restricted to classes this realm does not have are equippable by nobody
-- - dead loot that still drops and still fills quest reward pickers.
--
-- What replaces the gate: armor proficiency, which is a skill granted by a
-- spell and is locked to body type (docs/BODY-TYPES.md section 3). Plate stays
-- Vanguard-only because only a Paladin trains Plate Mail, not because the item
-- says so. The class mask was never doing that job; the skill was.
--
-- Rows touched: 4746 - weapons and armor whose stored mask does not already
-- admit all ten stock classes. Relics (armor subclass 7-10) are excluded: their
-- equip slot is chosen by a hardcoded IsClass() in Player::FindEquipSlot, so
-- clearing the mask would change nothing.
--
-- Reversible: classless_item_class_backup keeps the original value of every row
-- this touches. See docs/PHASE3-ITEMIZATION.md section 6 for the rollback.
--

CREATE TABLE IF NOT EXISTS `classless_item_class_backup` (
  `entry`                INT UNSIGNED NOT NULL,
  `AllowableClass`       INT          NOT NULL,
  `backed_up_at`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='mod-classless: pre-unlock AllowableClass, so the pass can be undone';

-- Snapshot first. INSERT IGNORE so re-running never overwrites a real original
-- with an already-unlocked -1.
INSERT IGNORE INTO `classless_item_class_backup` (`entry`, `AllowableClass`)
SELECT `entry`, `AllowableClass` FROM `item_template`
WHERE class IN (2,4) AND AllowableClass <> -1 AND (AllowableClass & 1535) <> 1535 AND NOT (class = 4 AND subclass BETWEEN 7 AND 10);

UPDATE `item_template` SET `AllowableClass` = -1
WHERE class IN (2,4) AND AllowableClass <> -1 AND (AllowableClass & 1535) <> 1535 AND NOT (class = 4 AND subclass BETWEEN 7 AND 10);
