--
-- Every race can be every body type.
--
-- GENERATED by tools/gen_body_types.py - do not hand-edit; re-run the tool.
--
-- Body types are built on real classes, and real classes are not available to
-- every race: only Draenei could be all three, and a Night Elf could be none
-- of them, so could not be created on this realm at all. That made race the
-- real character choice and body type a consequence of it, which is the
-- opposite of the design.
--
-- Approved 2026-08-31: add the rows rather than drop Night Elf.
--
-- A stock client will not OFFER these combinations - the creation screen reads
-- CharBaseInfo.dbc, and no server packet carries that list (docs/BODY-TYPES.md
-- section 4). The server accepting what the client does not yet offer costs
-- nothing and is the right shape for when the client patch ships.
--
-- Start position is copied from the race's own existing rows, so a Night Elf
-- Vanguard starts in Shadowglen like every other Night Elf. Action bars are
-- copied from a same-faction race that already has that class.
--
-- Reversible: every row added here is listed in classless_createinfo_added.
--

CREATE TABLE IF NOT EXISTS `classless_createinfo_added` (
  `race`  TINYINT UNSIGNED NOT NULL,
  `class` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`race`, `class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='mod-classless: race/class pairs this realm added, so they can be removed again';


-- Orc Vanguard (race 2, class 2), action bar from Blood Elf
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (2, 2);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (2, 2, 1, 14, -618.518, -4251.67, 38.718, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 2, 2, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 10 AND `class` = 2;

-- Night Elf Vanguard (race 4, class 2), action bar from Human
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (4, 2);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (4, 2, 1, 141, 10311.3, 832.463, 1326.41, 5.69632);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 4, 2, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 1 AND `class` = 2;

-- Undead Vanguard (race 5, class 2), action bar from Blood Elf
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (5, 2);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (5, 2, 0, 85, 1676.71, 1678.31, 121.67, 2.70526);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 5, 2, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 10 AND `class` = 2;

-- Tauren Vanguard (race 6, class 2), action bar from Blood Elf
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (6, 2);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (6, 2, 1, 215, -2917.58, -257.98, 52.9968, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 6, 2, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 10 AND `class` = 2;

-- Gnome Vanguard (race 7, class 2), action bar from Human
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (7, 2);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (7, 2, 0, 1, -6240.32, 331.033, 382.758, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 7, 2, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 1 AND `class` = 2;

-- Troll Vanguard (race 8, class 2), action bar from Blood Elf
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (8, 2);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (8, 2, 1, 14, -618.518, -4251.67, 38.718, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 8, 2, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 10 AND `class` = 2;

-- Human Skirmisher (race 1, class 7), action bar from Draenei
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (1, 7);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (1, 7, 0, 12, -8949.95, -132.493, 83.5312, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 1, 7, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 11 AND `class` = 7;

-- Dwarf Skirmisher (race 3, class 7), action bar from Draenei
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (3, 7);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (3, 7, 0, 1, -6240.32, 331.033, 382.758, 6.17716);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 3, 7, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 11 AND `class` = 7;

-- Night Elf Skirmisher (race 4, class 7), action bar from Draenei
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (4, 7);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (4, 7, 1, 141, 10311.3, 832.463, 1326.41, 5.69632);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 4, 7, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 11 AND `class` = 7;

-- Undead Skirmisher (race 5, class 7), action bar from Orc
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (5, 7);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (5, 7, 0, 85, 1676.71, 1678.31, 121.67, 2.70526);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 5, 7, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 2 AND `class` = 7;

-- Gnome Skirmisher (race 7, class 7), action bar from Draenei
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (7, 7);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (7, 7, 0, 1, -6240.32, 331.033, 382.758, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 7, 7, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 11 AND `class` = 7;

-- Blood Elf Skirmisher (race 10, class 7), action bar from Orc
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (10, 7);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (10, 7, 530, 3431, 10349.6, -6357.29, 33.4026, 5.31605);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 10, 7, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 2 AND `class` = 7;

-- Orc Adept (race 2, class 8), action bar from Undead
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (2, 8);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (2, 8, 1, 14, -618.518, -4251.67, 38.718, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 2, 8, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 5 AND `class` = 8;

-- Dwarf Adept (race 3, class 8), action bar from Human
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (3, 8);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (3, 8, 0, 1, -6240.32, 331.033, 382.758, 6.17716);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 3, 8, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 1 AND `class` = 8;

-- Night Elf Adept (race 4, class 8), action bar from Human
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (4, 8);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (4, 8, 1, 141, 10311.3, 832.463, 1326.41, 5.69632);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 4, 8, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 1 AND `class` = 8;

-- Tauren Adept (race 6, class 8), action bar from Undead
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (6, 8);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (6, 8, 1, 215, -2917.58, -257.98, 52.9968, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 6, 8, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 5 AND `class` = 8;
