--
-- Body-type stat curves for player_class_stats.
--
-- GENERATED by tools/gen_body_types.py - do not hand-edit; re-run the tool.
--
-- The numbers in docs/BODY-TYPES.md section 2 were approved on 2026-08-26 and
-- never turned into a migration, so until now the three body types were
-- numerically identical to stock Paladin, Shaman and Mage wearing new names.
--
-- Vanguard (Paladin, class 2) is the reference point and is not touched.
-- Skirmisher (Shaman, 7) and Adept (Mage, 8) are moved onto the approved
-- curve: linear from no change at level 1, through the approved level 60 row,
-- to the approved level 80 row. The generator refuses to emit unless both
-- anchors come out exactly and no stat decreases with level.
--
-- Reversible: classless_class_stats_backup keeps every original row.
--

CREATE TABLE IF NOT EXISTS `classless_class_stats_backup` (
  `Class`     TINYINT UNSIGNED NOT NULL,
  `Level`     TINYINT UNSIGNED NOT NULL,
  `BaseHP`    INT UNSIGNED NOT NULL,
  `BaseMana`  INT UNSIGNED NOT NULL,
  `Strength`  INT NOT NULL,
  `Agility`   INT NOT NULL,
  `Stamina`   INT NOT NULL,
  `Intellect` INT NOT NULL,
  `Spirit`    INT NOT NULL,
  PRIMARY KEY (`Class`, `Level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='mod-classless: pre-body-type player_class_stats, so the curve can be undone';

-- INSERT IGNORE so re-running never overwrites a real original with a value
-- this migration itself wrote.
INSERT IGNORE INTO `classless_class_stats_backup`
  (`Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
SELECT `Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`
FROM `player_class_stats` WHERE `Class` IN (3, 8);


-- Skirmisher (class 3): 78 of 80 levels differ from stock.
UPDATE `player_class_stats` SET `Stamina` = 24 WHERE `Class` = 3 AND `Level` = 3;
UPDATE `player_class_stats` SET `Stamina` = 24 WHERE `Class` = 3 AND `Level` = 4;
UPDATE `player_class_stats` SET `Stamina` = 25 WHERE `Class` = 3 AND `Level` = 5;
UPDATE `player_class_stats` SET `Stamina` = 26 WHERE `Class` = 3 AND `Level` = 6;
UPDATE `player_class_stats` SET `Stamina` = 28 WHERE `Class` = 3 AND `Level` = 7;
UPDATE `player_class_stats` SET `Stamina` = 29 WHERE `Class` = 3 AND `Level` = 8;
UPDATE `player_class_stats` SET `Stamina` = 30 WHERE `Class` = 3 AND `Level` = 9;
UPDATE `player_class_stats` SET `Stamina` = 30 WHERE `Class` = 3 AND `Level` = 10;
UPDATE `player_class_stats` SET `Stamina` = 32 WHERE `Class` = 3 AND `Level` = 11;
UPDATE `player_class_stats` SET `Stamina` = 33 WHERE `Class` = 3 AND `Level` = 12;
UPDATE `player_class_stats` SET `Stamina` = 34 WHERE `Class` = 3 AND `Level` = 13;
UPDATE `player_class_stats` SET `Stamina` = 35 WHERE `Class` = 3 AND `Level` = 14;
UPDATE `player_class_stats` SET `Stamina` = 37 WHERE `Class` = 3 AND `Level` = 15;
UPDATE `player_class_stats` SET `Stamina` = 38 WHERE `Class` = 3 AND `Level` = 16;
UPDATE `player_class_stats` SET `Stamina` = 39 WHERE `Class` = 3 AND `Level` = 17;
UPDATE `player_class_stats` SET `Stamina` = 40 WHERE `Class` = 3 AND `Level` = 18;
UPDATE `player_class_stats` SET `Stamina` = 42 WHERE `Class` = 3 AND `Level` = 19;
UPDATE `player_class_stats` SET `Stamina` = 43 WHERE `Class` = 3 AND `Level` = 20;
UPDATE `player_class_stats` SET `Stamina` = 44 WHERE `Class` = 3 AND `Level` = 21;
UPDATE `player_class_stats` SET `Stamina` = 45 WHERE `Class` = 3 AND `Level` = 22;
UPDATE `player_class_stats` SET `Stamina` = 47 WHERE `Class` = 3 AND `Level` = 23;
UPDATE `player_class_stats` SET `Stamina` = 48 WHERE `Class` = 3 AND `Level` = 24;
UPDATE `player_class_stats` SET `Stamina` = 49 WHERE `Class` = 3 AND `Level` = 25;
UPDATE `player_class_stats` SET `Stamina` = 50 WHERE `Class` = 3 AND `Level` = 26;
UPDATE `player_class_stats` SET `Stamina` = 52 WHERE `Class` = 3 AND `Level` = 27;
UPDATE `player_class_stats` SET `Stamina` = 53 WHERE `Class` = 3 AND `Level` = 28;
UPDATE `player_class_stats` SET `Stamina` = 54 WHERE `Class` = 3 AND `Level` = 29;
UPDATE `player_class_stats` SET `Stamina` = 55 WHERE `Class` = 3 AND `Level` = 30;
UPDATE `player_class_stats` SET `Stamina` = 58 WHERE `Class` = 3 AND `Level` = 31;
UPDATE `player_class_stats` SET `Stamina` = 59 WHERE `Class` = 3 AND `Level` = 32;
UPDATE `player_class_stats` SET `Stamina` = 60 WHERE `Class` = 3 AND `Level` = 33;
UPDATE `player_class_stats` SET `Stamina` = 61 WHERE `Class` = 3 AND `Level` = 34;
UPDATE `player_class_stats` SET `Stamina` = 63 WHERE `Class` = 3 AND `Level` = 35;
UPDATE `player_class_stats` SET `Stamina` = 65 WHERE `Class` = 3 AND `Level` = 36;
UPDATE `player_class_stats` SET `Stamina` = 66 WHERE `Class` = 3 AND `Level` = 37;
UPDATE `player_class_stats` SET `Stamina` = 67 WHERE `Class` = 3 AND `Level` = 38;
UPDATE `player_class_stats` SET `Stamina` = 69 WHERE `Class` = 3 AND `Level` = 39;
UPDATE `player_class_stats` SET `Stamina` = 71 WHERE `Class` = 3 AND `Level` = 40;
UPDATE `player_class_stats` SET `Stamina` = 72 WHERE `Class` = 3 AND `Level` = 41;
UPDATE `player_class_stats` SET `Stamina` = 73 WHERE `Class` = 3 AND `Level` = 42;
UPDATE `player_class_stats` SET `Stamina` = 75 WHERE `Class` = 3 AND `Level` = 43;
UPDATE `player_class_stats` SET `Stamina` = 77 WHERE `Class` = 3 AND `Level` = 44;
UPDATE `player_class_stats` SET `Stamina` = 78 WHERE `Class` = 3 AND `Level` = 45;
UPDATE `player_class_stats` SET `Stamina` = 80 WHERE `Class` = 3 AND `Level` = 46;
UPDATE `player_class_stats` SET `Stamina` = 82 WHERE `Class` = 3 AND `Level` = 47;
UPDATE `player_class_stats` SET `Stamina` = 83 WHERE `Class` = 3 AND `Level` = 48;
UPDATE `player_class_stats` SET `Stamina` = 85 WHERE `Class` = 3 AND `Level` = 49;
UPDATE `player_class_stats` SET `Stamina` = 86 WHERE `Class` = 3 AND `Level` = 50;
UPDATE `player_class_stats` SET `Stamina` = 89 WHERE `Class` = 3 AND `Level` = 51;
UPDATE `player_class_stats` SET `Stamina` = 90 WHERE `Class` = 3 AND `Level` = 52;
UPDATE `player_class_stats` SET `Stamina` = 92 WHERE `Class` = 3 AND `Level` = 53;
UPDATE `player_class_stats` SET `Stamina` = 93 WHERE `Class` = 3 AND `Level` = 54;
UPDATE `player_class_stats` SET `Stamina` = 96 WHERE `Class` = 3 AND `Level` = 55;
UPDATE `player_class_stats` SET `Stamina` = 97 WHERE `Class` = 3 AND `Level` = 56;
UPDATE `player_class_stats` SET `Stamina` = 99 WHERE `Class` = 3 AND `Level` = 57;
UPDATE `player_class_stats` SET `Stamina` = 101 WHERE `Class` = 3 AND `Level` = 58;
UPDATE `player_class_stats` SET `Stamina` = 103 WHERE `Class` = 3 AND `Level` = 59;
UPDATE `player_class_stats` SET `Stamina` = 105 WHERE `Class` = 3 AND `Level` = 60;
UPDATE `player_class_stats` SET `Stamina` = 107 WHERE `Class` = 3 AND `Level` = 61;
UPDATE `player_class_stats` SET `Stamina` = 109 WHERE `Class` = 3 AND `Level` = 62;
UPDATE `player_class_stats` SET `Stamina` = 111 WHERE `Class` = 3 AND `Level` = 63;
UPDATE `player_class_stats` SET `Stamina` = 113 WHERE `Class` = 3 AND `Level` = 64;
UPDATE `player_class_stats` SET `Stamina` = 115 WHERE `Class` = 3 AND `Level` = 65;
UPDATE `player_class_stats` SET `Stamina` = 116 WHERE `Class` = 3 AND `Level` = 66;
UPDATE `player_class_stats` SET `Stamina` = 119 WHERE `Class` = 3 AND `Level` = 67;
UPDATE `player_class_stats` SET `Stamina` = 121 WHERE `Class` = 3 AND `Level` = 68;
UPDATE `player_class_stats` SET `Stamina` = 123 WHERE `Class` = 3 AND `Level` = 69;
UPDATE `player_class_stats` SET `Stamina` = 126 WHERE `Class` = 3 AND `Level` = 70;
UPDATE `player_class_stats` SET `Stamina` = 128 WHERE `Class` = 3 AND `Level` = 71;
UPDATE `player_class_stats` SET `Stamina` = 130 WHERE `Class` = 3 AND `Level` = 72;
UPDATE `player_class_stats` SET `Stamina` = 132 WHERE `Class` = 3 AND `Level` = 73;
UPDATE `player_class_stats` SET `Stamina` = 134 WHERE `Class` = 3 AND `Level` = 74;
UPDATE `player_class_stats` SET `Stamina` = 137 WHERE `Class` = 3 AND `Level` = 75;
UPDATE `player_class_stats` SET `Stamina` = 139 WHERE `Class` = 3 AND `Level` = 76;
UPDATE `player_class_stats` SET `Stamina` = 141 WHERE `Class` = 3 AND `Level` = 77;
UPDATE `player_class_stats` SET `Stamina` = 144 WHERE `Class` = 3 AND `Level` = 78;
UPDATE `player_class_stats` SET `Stamina` = 146 WHERE `Class` = 3 AND `Level` = 79;
UPDATE `player_class_stats` SET `Stamina` = 148 WHERE `Class` = 3 AND `Level` = 80;

-- Adept (class 8): 79 of 80 levels differ from stock.
UPDATE `player_class_stats` SET `BaseHP` = 48, `BaseMana` = 115 WHERE `Class` = 8 AND `Level` = 2;
UPDATE `player_class_stats` SET `BaseHP` = 53, `BaseMana` = 116, `Strength` = 21, `Stamina` = 22 WHERE `Class` = 8 AND `Level` = 3;
UPDATE `player_class_stats` SET `BaseHP` = 69, `BaseMana` = 133, `Strength` = 21, `Agility` = 22, `Stamina` = 22, `Spirit` = 26 WHERE `Class` = 8 AND `Level` = 4;
UPDATE `player_class_stats` SET `BaseHP` = 84, `BaseMana` = 150, `Strength` = 21, `Agility` = 22, `Stamina` = 23, `Spirit` = 28 WHERE `Class` = 8 AND `Level` = 5;
UPDATE `player_class_stats` SET `BaseHP` = 100, `BaseMana` = 154, `Strength` = 22, `Agility` = 22, `Stamina` = 23, `Spirit` = 29 WHERE `Class` = 8 AND `Level` = 6;
UPDATE `player_class_stats` SET `BaseHP` = 105, `BaseMana` = 174, `Strength` = 23, `Agility` = 22, `Stamina` = 25, `Intellect` = 31, `Spirit` = 30 WHERE `Class` = 8 AND `Level` = 7;
UPDATE `player_class_stats` SET `BaseHP` = 121, `BaseMana` = 180, `Strength` = 23, `Agility` = 22, `Stamina` = 25, `Intellect` = 32, `Spirit` = 31 WHERE `Class` = 8 AND `Level` = 8;
UPDATE `player_class_stats` SET `BaseHP` = 136, `BaseMana` = 202, `Strength` = 23, `Agility` = 22, `Stamina` = 25, `Intellect` = 34, `Spirit` = 32 WHERE `Class` = 8 AND `Level` = 9;
UPDATE `player_class_stats` SET `BaseHP` = 142, `BaseMana` = 240, `Strength` = 23, `Agility` = 24, `Stamina` = 27, `Intellect` = 35, `Spirit` = 35 WHERE `Class` = 8 AND `Level` = 10;
UPDATE `player_class_stats` SET `BaseHP` = 157, `BaseMana` = 264, `Strength` = 24, `Agility` = 24, `Stamina` = 27, `Intellect` = 36, `Spirit` = 36 WHERE `Class` = 8 AND `Level` = 11;
UPDATE `player_class_stats` SET `BaseHP` = 173, `BaseMana` = 274, `Strength` = 24, `Agility` = 24, `Stamina` = 28, `Intellect` = 38, `Spirit` = 37 WHERE `Class` = 8 AND `Level` = 12;
UPDATE `player_class_stats` SET `BaseHP` = 178, `BaseMana` = 299, `Strength` = 24, `Agility` = 24, `Stamina` = 29, `Intellect` = 39, `Spirit` = 38 WHERE `Class` = 8 AND `Level` = 13;
UPDATE `player_class_stats` SET `BaseHP` = 194, `BaseMana` = 326, `Strength` = 25, `Agility` = 24, `Stamina` = 30, `Intellect` = 40, `Spirit` = 40 WHERE `Class` = 8 AND `Level` = 14;
UPDATE `player_class_stats` SET `BaseHP` = 209, `BaseMana` = 339, `Strength` = 26, `Agility` = 25, `Stamina` = 30, `Intellect` = 42, `Spirit` = 41 WHERE `Class` = 8 AND `Level` = 15;
UPDATE `player_class_stats` SET `BaseHP` = 215, `BaseMana` = 368, `Strength` = 26, `Agility` = 26, `Stamina` = 31, `Intellect` = 43, `Spirit` = 43 WHERE `Class` = 8 AND `Level` = 16;
UPDATE `player_class_stats` SET `BaseHP` = 230, `BaseMana` = 383, `Strength` = 26, `Agility` = 26, `Stamina` = 32, `Intellect` = 44, `Spirit` = 45 WHERE `Class` = 8 AND `Level` = 17;
UPDATE `player_class_stats` SET `BaseHP` = 246, `BaseMana` = 414, `Strength` = 26, `Agility` = 26, `Stamina` = 32, `Intellect` = 46, `Spirit` = 46 WHERE `Class` = 8 AND `Level` = 18;
UPDATE `player_class_stats` SET `BaseHP` = 251, `BaseMana` = 431, `Strength` = 27, `Agility` = 26, `Stamina` = 34, `Intellect` = 48, `Spirit` = 47 WHERE `Class` = 8 AND `Level` = 19;
UPDATE `player_class_stats` SET `BaseHP` = 267, `BaseMana` = 463, `Strength` = 27, `Agility` = 27, `Stamina` = 34, `Intellect` = 50, `Spirit` = 49 WHERE `Class` = 8 AND `Level` = 20;
UPDATE `player_class_stats` SET `BaseHP` = 282, `BaseMana` = 482, `Strength` = 28, `Agility` = 27, `Stamina` = 34, `Intellect` = 51, `Spirit` = 50 WHERE `Class` = 8 AND `Level` = 21;
UPDATE `player_class_stats` SET `BaseHP` = 288, `BaseMana` = 517, `Strength` = 28, `Agility` = 28, `Stamina` = 36, `Intellect` = 53, `Spirit` = 53 WHERE `Class` = 8 AND `Level` = 22;
UPDATE `player_class_stats` SET `BaseHP` = 303, `BaseMana` = 538, `Strength` = 29, `Agility` = 28, `Stamina` = 36, `Intellect` = 54, `Spirit` = 54 WHERE `Class` = 8 AND `Level` = 23;
UPDATE `player_class_stats` SET `BaseHP` = 310, `BaseMana` = 575, `Strength` = 29, `Agility` = 29, `Stamina` = 38, `Intellect` = 56, `Spirit` = 56 WHERE `Class` = 8 AND `Level` = 24;
UPDATE `player_class_stats` SET `BaseHP` = 327, `BaseMana` = 598, `Strength` = 29, `Agility` = 29, `Stamina` = 38, `Intellect` = 57, `Spirit` = 57 WHERE `Class` = 8 AND `Level` = 25;
UPDATE `player_class_stats` SET `BaseHP` = 346, `BaseMana` = 637, `Strength` = 29, `Agility` = 29, `Stamina` = 39, `Intellect` = 59, `Spirit` = 59 WHERE `Class` = 8 AND `Level` = 26;
UPDATE `player_class_stats` SET `BaseHP` = 355, `BaseMana` = 661, `Strength` = 30, `Agility` = 29, `Stamina` = 40, `Intellect` = 61, `Spirit` = 60 WHERE `Class` = 8 AND `Level` = 27;
UPDATE `player_class_stats` SET `BaseHP` = 376, `BaseMana` = 687, `Strength` = 31, `Agility` = 30, `Stamina` = 40, `Intellect` = 62, `Spirit` = 63 WHERE `Class` = 8 AND `Level` = 28;
UPDATE `player_class_stats` SET `BaseHP` = 387, `BaseMana` = 728, `Strength` = 31, `Agility` = 31, `Stamina` = 42, `Intellect` = 64, `Spirit` = 64 WHERE `Class` = 8 AND `Level` = 29;
UPDATE `player_class_stats` SET `BaseHP` = 410, `BaseMana` = 754, `Strength` = 31, `Agility` = 31, `Stamina` = 42, `Intellect` = 66, `Spirit` = 66 WHERE `Class` = 8 AND `Level` = 30;
UPDATE `player_class_stats` SET `BaseHP` = 433, `BaseMana` = 780, `Strength` = 32, `Agility` = 31, `Stamina` = 43, `Intellect` = 68, `Spirit` = 68 WHERE `Class` = 8 AND `Level` = 31;
UPDATE `player_class_stats` SET `BaseHP` = 448, `BaseMana` = 821, `Strength` = 32, `Agility` = 31, `Stamina` = 44, `Intellect` = 70, `Spirit` = 69 WHERE `Class` = 8 AND `Level` = 32;
UPDATE `player_class_stats` SET `BaseHP` = 473, `BaseMana` = 847, `Strength` = 32, `Agility` = 32, `Stamina` = 45, `Intellect` = 72, `Spirit` = 71 WHERE `Class` = 8 AND `Level` = 33;
UPDATE `player_class_stats` SET `BaseHP` = 490, `BaseMana` = 873, `Strength` = 33, `Agility` = 33, `Stamina` = 46, `Intellect` = 73, `Spirit` = 74 WHERE `Class` = 8 AND `Level` = 34;
UPDATE `player_class_stats` SET `BaseHP` = 517, `BaseMana` = 898, `Strength` = 34, `Agility` = 33, `Stamina` = 46, `Intellect` = 75, `Spirit` = 75 WHERE `Class` = 8 AND `Level` = 35;
UPDATE `player_class_stats` SET `BaseHP` = 536, `BaseMana` = 924, `Strength` = 34, `Agility` = 34, `Stamina` = 48, `Intellect` = 77, `Spirit` = 77 WHERE `Class` = 8 AND `Level` = 36;
UPDATE `player_class_stats` SET `BaseHP` = 565, `BaseMana` = 965, `Strength` = 34, `Agility` = 34, `Stamina` = 48, `Intellect` = 79, `Spirit` = 79 WHERE `Class` = 8 AND `Level` = 37;
UPDATE `player_class_stats` SET `BaseHP` = 596, `BaseMana` = 991, `Strength` = 34, `Agility` = 34, `Stamina` = 49, `Intellect` = 81, `Spirit` = 81 WHERE `Class` = 8 AND `Level` = 38;
UPDATE `player_class_stats` SET `BaseHP` = 617, `BaseMana` = 1017, `Strength` = 36, `Agility` = 34, `Stamina` = 50, `Intellect` = 83, `Spirit` = 82 WHERE `Class` = 8 AND `Level` = 39;
UPDATE `player_class_stats` SET `BaseHP` = 650, `BaseMana` = 1043, `Strength` = 36, `Agility` = 36, `Stamina` = 51, `Intellect` = 84, `Spirit` = 85 WHERE `Class` = 8 AND `Level` = 40;
UPDATE `player_class_stats` SET `BaseHP` = 673, `BaseMana` = 1069, `Strength` = 36, `Agility` = 36, `Stamina` = 52, `Intellect` = 86, `Spirit` = 87 WHERE `Class` = 8 AND `Level` = 41;
UPDATE `player_class_stats` SET `BaseHP` = 708, `BaseMana` = 1094, `Strength` = 36, `Agility` = 36, `Stamina` = 52, `Intellect` = 88, `Spirit` = 89 WHERE `Class` = 8 AND `Level` = 42;
UPDATE `player_class_stats` SET `BaseHP` = 733, `BaseMana` = 1120, `Strength` = 37, `Agility` = 36, `Stamina` = 54, `Intellect` = 91, `Spirit` = 91 WHERE `Class` = 8 AND `Level` = 43;
UPDATE `player_class_stats` SET `BaseHP` = 770, `BaseMana` = 1146, `Strength` = 37, `Agility` = 37, `Stamina` = 54, `Intellect` = 93, `Spirit` = 93 WHERE `Class` = 8 AND `Level` = 44;
UPDATE `player_class_stats` SET `BaseHP` = 797, `BaseMana` = 1172, `Strength` = 38, `Agility` = 37, `Stamina` = 56, `Intellect` = 95, `Spirit` = 95 WHERE `Class` = 8 AND `Level` = 45;
UPDATE `player_class_stats` SET `BaseHP` = 836, `BaseMana` = 1198, `Strength` = 38, `Agility` = 38, `Stamina` = 56, `Intellect` = 97, `Spirit` = 98 WHERE `Class` = 8 AND `Level` = 46;
UPDATE `player_class_stats` SET `BaseHP` = 865, `BaseMana` = 1224, `Strength` = 39, `Agility` = 39, `Stamina` = 57, `Intellect` = 99, `Spirit` = 100 WHERE `Class` = 8 AND `Level` = 47;
UPDATE `player_class_stats` SET `BaseHP` = 906, `BaseMana` = 1250, `Strength` = 39, `Agility` = 39, `Stamina` = 58, `Intellect` = 102, `Spirit` = 102 WHERE `Class` = 8 AND `Level` = 48;
UPDATE `player_class_stats` SET `BaseHP` = 937, `BaseMana` = 1275, `Strength` = 40, `Agility` = 39, `Stamina` = 59, `Intellect` = 104, `Spirit` = 104 WHERE `Class` = 8 AND `Level` = 49;
UPDATE `player_class_stats` SET `BaseHP` = 980, `BaseMana` = 1286, `Strength` = 40, `Agility` = 40, `Stamina` = 60, `Intellect` = 106, `Spirit` = 106 WHERE `Class` = 8 AND `Level` = 50;
UPDATE `player_class_stats` SET `BaseHP` = 1013, `BaseMana` = 1312, `Strength` = 41, `Agility` = 40, `Stamina` = 61, `Intellect` = 108, `Spirit` = 108 WHERE `Class` = 8 AND `Level` = 51;
UPDATE `player_class_stats` SET `BaseHP` = 1058, `BaseMana` = 1338, `Strength` = 41, `Agility` = 41, `Stamina` = 62, `Intellect` = 110, `Spirit` = 111 WHERE `Class` = 8 AND `Level` = 52;
UPDATE `player_class_stats` SET `BaseHP` = 1093, `BaseMana` = 1364, `Strength` = 41, `Agility` = 42, `Stamina` = 63, `Intellect` = 112, `Spirit` = 113 WHERE `Class` = 8 AND `Level` = 53;
UPDATE `player_class_stats` SET `BaseHP` = 1130, `BaseMana` = 1375, `Strength` = 42, `Agility` = 42, `Stamina` = 64, `Intellect` = 115, `Spirit` = 115 WHERE `Class` = 8 AND `Level` = 54;
UPDATE `player_class_stats` SET `BaseHP` = 1177, `BaseMana` = 1401, `Strength` = 43, `Agility` = 42, `Stamina` = 65, `Intellect` = 118, `Spirit` = 118 WHERE `Class` = 8 AND `Level` = 55;
UPDATE `player_class_stats` SET `BaseHP` = 1216, `BaseMana` = 1427, `Strength` = 43, `Agility` = 43, `Stamina` = 66, `Intellect` = 120, `Spirit` = 120 WHERE `Class` = 8 AND `Level` = 56;
UPDATE `player_class_stats` SET `BaseHP` = 1265, `BaseMana` = 1437, `Strength` = 43, `Agility` = 43, `Stamina` = 67, `Intellect` = 123, `Spirit` = 122 WHERE `Class` = 8 AND `Level` = 57;
UPDATE `player_class_stats` SET `BaseHP` = 1306, `BaseMana` = 1463, `Strength` = 44, `Agility` = 44, `Stamina` = 68, `Intellect` = 125, `Spirit` = 125 WHERE `Class` = 8 AND `Level` = 58;
UPDATE `player_class_stats` SET `BaseHP` = 1357, `BaseMana` = 1474, `Strength` = 45, `Agility` = 45, `Stamina` = 69, `Intellect` = 128, `Spirit` = 128 WHERE `Class` = 8 AND `Level` = 59;
UPDATE `player_class_stats` SET `BaseHP` = 1400, `BaseMana` = 1500, `Strength` = 45, `Agility` = 45, `Stamina` = 70, `Intellect` = 130, `Spirit` = 130 WHERE `Class` = 8 AND `Level` = 60;
UPDATE `player_class_stats` SET `BaseHP` = 1561, `BaseMana` = 1645, `Strength` = 45, `Agility` = 45, `Stamina` = 72, `Intellect` = 132, `Spirit` = 132 WHERE `Class` = 8 AND `Level` = 61;
UPDATE `player_class_stats` SET `BaseHP` = 1743, `BaseMana` = 1791, `Strength` = 45, `Agility` = 46, `Stamina` = 74, `Intellect` = 135, `Spirit` = 135 WHERE `Class` = 8 AND `Level` = 62;
UPDATE `player_class_stats` SET `BaseHP` = 1921, `BaseMana` = 1935, `Strength` = 47, `Agility` = 46, `Stamina` = 76, `Intellect` = 139, `Spirit` = 136 WHERE `Class` = 8 AND `Level` = 63;
UPDATE `player_class_stats` SET `BaseHP` = 2121, `BaseMana` = 2080, `Strength` = 47, `Agility` = 46, `Stamina` = 77, `Intellect` = 141, `Spirit` = 139 WHERE `Class` = 8 AND `Level` = 64;
UPDATE `player_class_stats` SET `BaseHP` = 2318, `BaseMana` = 2225, `Strength` = 47, `Agility` = 47, `Stamina` = 80, `Intellect` = 144, `Spirit` = 141 WHERE `Class` = 8 AND `Level` = 65;
UPDATE `player_class_stats` SET `BaseHP` = 2523, `BaseMana` = 2370, `Strength` = 48, `Agility` = 48, `Stamina` = 82, `Intellect` = 146, `Spirit` = 144 WHERE `Class` = 8 AND `Level` = 66;
UPDATE `player_class_stats` SET `BaseHP` = 2753, `BaseMana` = 2515, `Strength` = 48, `Agility` = 49, `Stamina` = 83, `Intellect` = 149, `Spirit` = 146 WHERE `Class` = 8 AND `Level` = 67;
UPDATE `player_class_stats` SET `BaseHP` = 2979, `BaseMana` = 2660, `Strength` = 49, `Agility` = 49, `Stamina` = 85, `Intellect` = 153, `Spirit` = 148 WHERE `Class` = 8 AND `Level` = 68;
UPDATE `player_class_stats` SET `BaseHP` = 3214, `BaseMana` = 2805, `Strength` = 49, `Agility` = 49, `Stamina` = 88, `Intellect` = 156, `Spirit` = 151 WHERE `Class` = 8 AND `Level` = 69;
UPDATE `player_class_stats` SET `BaseHP` = 3477, `BaseMana` = 2951, `Strength` = 50, `Agility` = 50, `Stamina` = 89, `Intellect` = 158, `Spirit` = 153 WHERE `Class` = 8 AND `Level` = 70;
UPDATE `player_class_stats` SET `BaseHP` = 3735, `BaseMana` = 3095, `Strength` = 50, `Agility` = 50, `Stamina` = 91, `Intellect` = 161, `Spirit` = 156 WHERE `Class` = 8 AND `Level` = 71;
UPDATE `player_class_stats` SET `BaseHP` = 4012, `BaseMana` = 3240, `Strength` = 50, `Agility` = 51, `Stamina` = 94, `Intellect` = 164, `Spirit` = 159 WHERE `Class` = 8 AND `Level` = 72;
UPDATE `player_class_stats` SET `BaseHP` = 4310, `BaseMana` = 3385, `Strength` = 51, `Agility` = 51, `Stamina` = 96, `Intellect` = 168, `Spirit` = 161 WHERE `Class` = 8 AND `Level` = 73;
UPDATE `player_class_stats` SET `BaseHP` = 4629, `BaseMana` = 3530, `Strength` = 52, `Agility` = 52, `Stamina` = 97, `Intellect` = 171, `Spirit` = 163 WHERE `Class` = 8 AND `Level` = 74;
UPDATE `player_class_stats` SET `BaseHP` = 4971, `BaseMana` = 3675, `Strength` = 52, `Agility` = 53, `Stamina` = 99, `Intellect` = 174, `Spirit` = 166 WHERE `Class` = 8 AND `Level` = 75;
UPDATE `player_class_stats` SET `BaseHP` = 5339, `BaseMana` = 3820, `Strength` = 52, `Agility` = 53, `Stamina` = 102, `Intellect` = 177, `Spirit` = 169 WHERE `Class` = 8 AND `Level` = 76;
UPDATE `player_class_stats` SET `BaseHP` = 5733, `BaseMana` = 3965, `Strength` = 53, `Agility` = 54, `Stamina` = 104, `Intellect` = 180, `Spirit` = 172 WHERE `Class` = 8 AND `Level` = 77;
UPDATE `player_class_stats` SET `BaseHP` = 6156, `BaseMana` = 4111, `Strength` = 54, `Agility` = 54, `Stamina` = 105, `Intellect` = 184, `Spirit` = 174 WHERE `Class` = 8 AND `Level` = 78;
UPDATE `player_class_stats` SET `BaseHP` = 6612, `BaseMana` = 4255, `Strength` = 54, `Agility` = 55, `Stamina` = 108, `Intellect` = 187, `Spirit` = 177 WHERE `Class` = 8 AND `Level` = 79;
UPDATE `player_class_stats` SET `BaseHP` = 7100, `BaseMana` = 4400, `Strength` = 55, `Agility` = 55, `Stamina` = 110, `Intellect` = 190, `Spirit` = 180 WHERE `Class` = 8 AND `Level` = 80;
