--
-- Every race can be every body type.
--
-- GENERATED by tools/gen_body_types.py - do not hand-edit; re-run the tool.
--
-- Body types are built on real classes, and real classes are not available to
-- every race: only Draenei could be all three, and a Night Elf could be none
-- of them, so could not be created on this realm at all. That made race the
-- real character choice and body type a consequence of it, which is the
-- opposite of the design.
--
-- Approved 2026-08-31: add the rows rather than drop Night Elf.
--
-- A stock client will not OFFER these combinations - the creation screen reads
-- CharBaseInfo.dbc, and no server packet carries that list (docs/BODY-TYPES.md
-- section 4). The server accepting what the client does not yet offer costs
-- nothing and is the right shape for when the client patch ships.
--
-- Start position is copied from the race's own existing rows, so a Night Elf
-- Vanguard starts in Shadowglen like every other Night Elf. Action bars are
-- copied from a same-faction race that already has that class.
--
-- Reversible: every row added here is listed in classless_createinfo_added.
--

CREATE TABLE IF NOT EXISTS `classless_createinfo_added` (
  `race`  TINYINT UNSIGNED NOT NULL,
  `class` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`race`, `class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='mod-classless: race/class pairs this realm added, so they can be removed again';


-- Human Skirmisher (race 1, class 3), action bar from Dwarf
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (1, 3);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (1, 3, 0, 12, -8949.95, -132.493, 83.5312, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 1, 3, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 3 AND `class` = 3;

-- Undead Skirmisher (race 5, class 3), action bar from Orc
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (5, 3);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (5, 3, 0, 85, 1676.71, 1678.31, 121.67, 2.70526);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 5, 3, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 2 AND `class` = 3;

-- Gnome Skirmisher (race 7, class 3), action bar from Dwarf
INSERT IGNORE INTO `classless_createinfo_added` (`race`, `class`) VALUES (7, 3);
INSERT IGNORE INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES (7, 3, 0, 1, -6240.32, 331.033, 382.758, 0);
INSERT IGNORE INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) SELECT 7, 3, `button`, `action`, `type` FROM `playercreateinfo_action` WHERE `race` = 3 AND `class` = 3;
